---
- name: Provision server
  hosts: all
  remote_user: ec2-user
  gather_facts: no
  vars:
    ansible_ssh_pipelining: no
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    splunk_target_layer: "app"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vars/all_var.yml"
  tasks:
    - name: Apply security patches
      become_user: "{{ remote_admin_account }}"
      become: yes
      command: "yum update-minimal --security -y"
    - name: Install dependencies
      become: yes
      become_user: "{{ remote_admin_account }}"
      yum:
        name:
          - gcc
          - git
          - python3-devel
          - postgresql-devel
          - zlib-devel
          - libjpeg-turbo-devel
          - nginx
          - ansible
          - amazon-cloudwatch-agent
    - name: Install uwsgi via pip
      become: yes
      become_user: "{{ remote_admin_account }}"
      pip:
        name: uwsgi
        executable: pip3
        umask: "0022"
    - name: Copy cloudwatch agent base config file
      become_user: "{{ remote_admin_account }}"
      become: yes
      template:
        src: templates/cwagent.json.j2
        dest: /tmp/cwagent-base.json
    - name: Start cloudwatch agent with base config
      become_user: "{{ remote_admin_account }}"
      become: yes
      shell: "amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/tmp/cwagent-base.json -s"